print("Good morning")
print("My name is Keji, what is your name?")
person = input()
print("how old are you?")
age = int(input())
print("Hi", person, "of this", age, "year", "Welcome to my greeting session")